# Generated by Django 6.0.1 on 2026-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='editada',
            field=models.BooleanField(default=False),
        ),
    ]
