# Generated by Django 6.0.1 on 2026-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensagem_editada'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_anexos/'),
        ),
    ]
