# Generated by Django 6.0.1 on 2026-02-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_arquivos/'),
        ),
    ]
