# Generated by Django 6.0.1 on 2026-01-22 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rotas', '0008_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('protocolo', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('produto_nome', models.CharField(max_length=140)),
                ('marca', models.CharField(max_length=80)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('fardo', 'Fardo'), ('kg', 'Kg'), ('l', 'Litro')], default='un', max_length=10)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=60)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_destino', to='rotas.loja')),
                ('loja_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_origem', to='rotas.loja')),
            ],
        ),
    ]
