# Generated by Django 6.0.1 on 2026-01-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimentoEstoque',
        ),
    ]
