# Generated by Django 6.0.1 on 2026-01-15 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, default='', max_length=80)),
                ('ativa', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado'), ('problema', 'Problema')], default='pendente', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='rotas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado'), ('problema', 'Problema')], default='pendente', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rotas.loja')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rotas.rota')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('rota', 'ordem')},
            },
        ),
    ]
