# Generated by Django 6.0.1 on 2026-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
