# Generated by Django 6.0.1 on 2026-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_parada_collected_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='longitude',
            new_name='lng',
        ),
    ]
