# Generated by Django 6.0.1 on 2026-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_rename_latitude_loja_lat_rename_longitude_loja_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='endereco_normalizado',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
