# Generated by Django 6.0.1 on 2026-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0004_loja_endereco_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='loja',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='loja',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='loja',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
