# Generated by Django 6.0.1 on 2026-01-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0007_protocolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('saida', 'Saída (CD → Loja)'), ('entrada', 'Entrada (Loja → CD)')], max_length=20)),
                ('retirado_por_nome', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='rotas.loja')),
                ('motorista', models.ForeignKey(blank=True, help_text='Motoboy responsável por confirmar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
