# Generated by Django 6.0.1 on 2026-01-23 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0008_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parada',
            options={},
        ),
        migrations.RenameField(
            model_name='parada',
            old_name='collected_at',
            new_name='coletado_em',
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='parada',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='rota',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='motoboy',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='protocolo',
        ),
        migrations.AddField(
            model_name='coleta',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loja',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parada',
            name='data_hora_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parada',
            name='visitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rota',
            name='nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='loja_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transf_destino_set', to='rotas.loja'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='loja_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transf_origem_set', to='rotas.loja'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='retirado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotas.loja'),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_rota', 'Em rota'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='bairro',
            field=models.CharField(default='Centro', max_length=120),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cidade',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='loja',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(default='Rua Exemplo, 123', max_length=255),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco_normalizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='numero',
            field=models.CharField(default='S/N', max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='uf',
            field=models.CharField(default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='parada',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotas.loja'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parada',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotas.rota'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='confirmado_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='rotas.loja'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rota',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_rota', 'Em rota'), ('finalizada', 'Finalizada')], default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rotas.loja'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_motorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='retirado_por_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(choices=[('cd_para_loja', 'CD -> Loja'), ('loja_para_cd', 'Loja -> CD')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='parada',
            name='status',
        ),
    ]
