# Generated by Django 6.0.1 on 2026-01-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0009_movimentoestoque_alter_parada_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parada',
            old_name='coletado_em',
            new_name='collected_at',
        ),
        migrations.AddField(
            model_name='parada',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='parada',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rotas.rota'),
        ),
    ]
