# Generated by Django 6.0.1 on 2026-01-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0010_rename_coletado_em_parada_collected_at_parada_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='motorista',
            new_name='motoboy',
        ),
    ]
