# Generated by Django 6.0.1 on 2026-01-23 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0011_rename_motorista_rota_motoboy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loja_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso'),
        ),
    ]
