# Generated by Django 6.0.1 on 2026-01-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0012_loja_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='rotas.rota', verbose_name='Rota Vinculada'),
        ),
    ]
