# Generated by Django 6.0.1 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0013_transferencia_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='tamanho_carga',
            field=models.CharField(choices=[('pequeno', 'Pequeno (Motoboy)'), ('medio', 'Médio (Utilitário)'), ('grande', 'Grande (Caminhão)')], default='pequeno', max_length=10),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('confirmada', 'Confirmada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20),
        ),
    ]
