# Generated by Django 6.0.1 on 2026-01-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0014_transferencia_tamanho_carga_alter_coleta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='numero_transferencia',
            field=models.CharField(default='0', max_length=50, verbose_name='Nº da Transferência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='porte_carga',
            field=models.CharField(choices=[('pequeno', 'Pequeno (Motoboy)'), ('grande', 'Grande (Motorista/Carro)')], default='pequeno', max_length=10, verbose_name='Porte da Carga'),
        ),
    ]
