# Generated by Django 6.0.1 on 2026-03-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0018_rota_created_at_rota_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='confirmada_cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='confirmada_cd_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='confirmada_cd_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_confirmadas_cd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='obs_confirmacao_cd',
            field=models.TextField(blank=True, default=''),
        ),
    ]
