# Generated by Django 6.0.1 on 2026-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0019_transferencia_confirmada_cd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='data',
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('aguardando_cd', 'Aguardando confirmação CD'), ('confirmada', 'Confirmada')], default='pendente', max_length=20),
        ),
    ]
