# Generated by Django 6.0.1 on 2026-05-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0020_remove_movimentoestoque_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='rotas.loja'),
        ),
    ]
